### ISSUE TITLE
Support removing item from the middle of the queue

### ISSUE THREAD

**Issue by gdoron** [jasonsjones/queue-fifo#4]
Hi,
Since this package uses double linked list as its underlying data structure, it would be possible to remove an item from the middle of the queue without the need to take all the items from the queue and return n-1 of them again to the queue.

Thanks,
Doron

**Comment by jasonsjones** [comment]
Hi Doron, Thanks for taking the time to open this feature request issue.

While it would be technically possible to add a feature to this _queue_ data structure to remove an element from the middle of the queue, I am a bit hesitant to increase the API surface area to add functionality that does not necessarily belong to a _first-in-first-out_ data structure. Because as soon as I do, well...then we wouldn't really have a _queue_.

That said, if you have a requirement for such functionality in your project, have you considered utilizing a different data structure that may meet your needs out of the box? For example, as you highlight in the issue, I'm using a _doubly linked list_ as the underlying data structure for this queue. This data structure provides the means to remove any node from the list, regardless of position. I suggest looking into something like that to meet this requirement.

Thanks!

**Comment by gdoron** [comment]
Actually, I ended up (ab?)using the _queue-fifo_ library.
And for the need to remove an item from the queue, I used the "private" property `_list` like this:

    let currentNode = availableProxies._list.head;
    let proxyObject;
    while (currentNode != null) {
        if (currentNode.data.ip == ip && currentNode.data.port == port) {
            availableProxies._list.removeNode(currentNode.data)
            proxyObject = urrentHead.data;
            break;
        }

        currentNode = currentNode.next;
    }
    if (proxyObject == null) {
        res.status(400).json({ error: 'Unknown proxy' });
        return;
    }

The story behind this code is, I have a list of proxies I'm using, for various use-cases.
I want to distribute my work on them equally, so I've put them in a queue, and every time I need a proxy to do something, I take an item out of the queue and enqueue it again.

And when the consumer report the queue is broken, I need to take it out of the queue.

I don't think it's a rare requirement not suitable for a queue.
And the implementation can be encapsulated, it doesn't really matter if it takes all the items out of the queue and put them all minus 1 back to the queue, or use linked-list feature of removing a node.

I would add a method:

```
function remove(nodeData, predicateFunction){
}
```
Where `predicateFunction` is a function that will be used to compare nodeData to the `.data` property.

What do you think @jasonsjones?

If you agree with the proposal, I'll open a MR for this.

**Comment by jasonsjones** [comment]
@gdoron -- Hi Doron, thanks for providing the additional context--it definitely helps me understand your use case a bit better. And it seems that you were able to implement a work-around for your case, albeit a bit invasive, but a work-around nonetheless :wink:. I do understand sometimes you have to do what you have to do 🙂 

I also appreciate the offer to help implement the requested functionality; you're very persuasive. However, to be honest, I have to respectfully disagree with the statement that implies a `remove` (in the middle of the queue) operation is a common requirement that would be suitable for a queue. I don't mean to be overly pedantic here, I just want to keep the scope of the library focused on a basic `queue` data structure and not increase the API surface area with non-standard `queue` operations.

While it does seem for the use-case you describe, a `queue` would suffice for most scenarios, however, as soon as you find yourself with the need to deviate from what a `queue` provides, it seems to me, you end up in a state where you need a more 'custom' data structure. But I do understand wanting to leverage what is already out there, and am humbled you initially considered to use this library.  That said, feel free to fork this and implement the deviations you need, that is the beauty of open source after all.

I greatly appreciate this discussion and your willingness to make the effort to solve your problem. Thanks!
